/*
 * generated by Xtext 2.36.0
 */
package fr.imt.bertin.dala.project.parser.antlr;

import com.google.inject.Inject;
import fr.imt.bertin.dala.project.parser.antlr.internal.InternalBrowserParser;
import fr.imt.bertin.dala.project.services.BrowserGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class BrowserParser extends AbstractAntlrParser {

	@Inject
	private BrowserGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalBrowserParser createParser(XtextTokenStream stream) {
		return new InternalBrowserParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public BrowserGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(BrowserGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
