/*
 * generated by Xtext 2.36.0
 */
package fr.imt.bertin.dala.project.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class BrowserAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("fr/imt/bertin/dala/project/parser/antlr/internal/InternalBrowser.tokens");
	}
}
