/*
 * generated by Xtext 2.36.0
 */
package fr.imt.bertin.dala.project;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BrowserRuntimeModule extends AbstractBrowserRuntimeModule {
}
