/**
 * generated by Xtext 2.36.0
 */
package fr.imt.bertin.dala.project.browser;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see fr.imt.bertin.dala.project.browser.BrowserFactory
 * @model kind="package"
 * @generated
 */
public interface BrowserPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "browser";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.imt.fr/bertin/dala/project/Browser";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "browser";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  BrowserPackage eINSTANCE = fr.imt.bertin.dala.project.browser.impl.BrowserPackageImpl.init();

  /**
   * The meta object id for the '{@link fr.imt.bertin.dala.project.browser.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.imt.bertin.dala.project.browser.impl.ModelImpl
   * @see fr.imt.bertin.dala.project.browser.impl.BrowserPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__STATEMENTS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.imt.bertin.dala.project.browser.impl.StatementImpl <em>Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.imt.bertin.dala.project.browser.impl.StatementImpl
   * @see fr.imt.bertin.dala.project.browser.impl.BrowserPackageImpl#getStatement()
   * @generated
   */
  int STATEMENT = 1;

  /**
   * The number of structural features of the '<em>Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link fr.imt.bertin.dala.project.browser.impl.OpenUrlImpl <em>Open Url</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.imt.bertin.dala.project.browser.impl.OpenUrlImpl
   * @see fr.imt.bertin.dala.project.browser.impl.BrowserPackageImpl#getOpenUrl()
   * @generated
   */
  int OPEN_URL = 2;

  /**
   * The feature id for the '<em><b>Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPEN_URL__URL = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Open Url</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPEN_URL_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.imt.bertin.dala.project.browser.impl.ClickLinkImpl <em>Click Link</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.imt.bertin.dala.project.browser.impl.ClickLinkImpl
   * @see fr.imt.bertin.dala.project.browser.impl.BrowserPackageImpl#getClickLink()
   * @generated
   */
  int CLICK_LINK = 3;

  /**
   * The feature id for the '<em><b>Link Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK_LINK__LINK_TEXT = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Click Link</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK_LINK_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.imt.bertin.dala.project.browser.impl.ClickImageImpl <em>Click Image</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.imt.bertin.dala.project.browser.impl.ClickImageImpl
   * @see fr.imt.bertin.dala.project.browser.impl.BrowserPackageImpl#getClickImage()
   * @generated
   */
  int CLICK_IMAGE = 4;

  /**
   * The feature id for the '<em><b>Alt Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK_IMAGE__ALT_TEXT = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Click Image</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK_IMAGE_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.imt.bertin.dala.project.browser.impl.VerifyLinkImpl <em>Verify Link</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.imt.bertin.dala.project.browser.impl.VerifyLinkImpl
   * @see fr.imt.bertin.dala.project.browser.impl.BrowserPackageImpl#getVerifyLink()
   * @generated
   */
  int VERIFY_LINK = 5;

  /**
   * The feature id for the '<em><b>Texts</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERIFY_LINK__TEXTS = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Verify Link</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERIFY_LINK_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.imt.bertin.dala.project.browser.impl.FillTextImpl <em>Fill Text</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.imt.bertin.dala.project.browser.impl.FillTextImpl
   * @see fr.imt.bertin.dala.project.browser.impl.BrowserPackageImpl#getFillText()
   * @generated
   */
  int FILL_TEXT = 6;

  /**
   * The feature id for the '<em><b>Text</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILL_TEXT__TEXT = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Field</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILL_TEXT__FIELD = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Fill Text</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILL_TEXT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.imt.bertin.dala.project.browser.impl.ClickButtonImpl <em>Click Button</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.imt.bertin.dala.project.browser.impl.ClickButtonImpl
   * @see fr.imt.bertin.dala.project.browser.impl.BrowserPackageImpl#getClickButton()
   * @generated
   */
  int CLICK_BUTTON = 7;

  /**
   * The feature id for the '<em><b>Button Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK_BUTTON__BUTTON_TEXT = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Click Button</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK_BUTTON_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.imt.bertin.dala.project.browser.impl.VerifyTextImpl <em>Verify Text</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.imt.bertin.dala.project.browser.impl.VerifyTextImpl
   * @see fr.imt.bertin.dala.project.browser.impl.BrowserPackageImpl#getVerifyText()
   * @generated
   */
  int VERIFY_TEXT = 8;

  /**
   * The feature id for the '<em><b>Texts</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERIFY_TEXT__TEXTS = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Verify Text</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERIFY_TEXT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.imt.bertin.dala.project.browser.impl.SelectOptionImpl <em>Select Option</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.imt.bertin.dala.project.browser.impl.SelectOptionImpl
   * @see fr.imt.bertin.dala.project.browser.impl.BrowserPackageImpl#getSelectOption()
   * @generated
   */
  int SELECT_OPTION = 9;

  /**
   * The feature id for the '<em><b>Link Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_OPTION__LINK_TEXT = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Select Option</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_OPTION_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.imt.bertin.dala.project.browser.impl.CheckCheckboxesImpl <em>Check Checkboxes</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.imt.bertin.dala.project.browser.impl.CheckCheckboxesImpl
   * @see fr.imt.bertin.dala.project.browser.impl.BrowserPackageImpl#getCheckCheckboxes()
   * @generated
   */
  int CHECK_CHECKBOXES = 10;

  /**
   * The feature id for the '<em><b>Items</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECK_CHECKBOXES__ITEMS = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Check Checkboxes</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECK_CHECKBOXES_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.imt.bertin.dala.project.browser.impl.SaveLinkImpl <em>Save Link</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.imt.bertin.dala.project.browser.impl.SaveLinkImpl
   * @see fr.imt.bertin.dala.project.browser.impl.BrowserPackageImpl#getSaveLink()
   * @generated
   */
  int SAVE_LINK = 11;

  /**
   * The feature id for the '<em><b>Index</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SAVE_LINK__INDEX = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Container</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SAVE_LINK__CONTAINER = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Save Link</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SAVE_LINK_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.imt.bertin.dala.project.browser.impl.TextPartImpl <em>Text Part</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.imt.bertin.dala.project.browser.impl.TextPartImpl
   * @see fr.imt.bertin.dala.project.browser.impl.BrowserPackageImpl#getTextPart()
   * @generated
   */
  int TEXT_PART = 12;

  /**
   * The number of structural features of the '<em>Text Part</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_PART_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link fr.imt.bertin.dala.project.browser.impl.StringLiteralImpl <em>String Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.imt.bertin.dala.project.browser.impl.StringLiteralImpl
   * @see fr.imt.bertin.dala.project.browser.impl.BrowserPackageImpl#getStringLiteral()
   * @generated
   */
  int STRING_LITERAL = 13;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_LITERAL__VALUE = TEXT_PART_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>String Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_LITERAL_FEATURE_COUNT = TEXT_PART_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.imt.bertin.dala.project.browser.impl.VariableReferenceImpl <em>Variable Reference</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.imt.bertin.dala.project.browser.impl.VariableReferenceImpl
   * @see fr.imt.bertin.dala.project.browser.impl.BrowserPackageImpl#getVariableReference()
   * @generated
   */
  int VARIABLE_REFERENCE = 14;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_REFERENCE__NAME = TEXT_PART_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Variable Reference</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_REFERENCE_FEATURE_COUNT = TEXT_PART_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link fr.imt.bertin.dala.project.browser.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see fr.imt.bertin.dala.project.browser.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link fr.imt.bertin.dala.project.browser.Model#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see fr.imt.bertin.dala.project.browser.Model#getStatements()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Statements();

  /**
   * Returns the meta object for class '{@link fr.imt.bertin.dala.project.browser.Statement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Statement</em>'.
   * @see fr.imt.bertin.dala.project.browser.Statement
   * @generated
   */
  EClass getStatement();

  /**
   * Returns the meta object for class '{@link fr.imt.bertin.dala.project.browser.OpenUrl <em>Open Url</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Open Url</em>'.
   * @see fr.imt.bertin.dala.project.browser.OpenUrl
   * @generated
   */
  EClass getOpenUrl();

  /**
   * Returns the meta object for the attribute '{@link fr.imt.bertin.dala.project.browser.OpenUrl#getUrl <em>Url</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Url</em>'.
   * @see fr.imt.bertin.dala.project.browser.OpenUrl#getUrl()
   * @see #getOpenUrl()
   * @generated
   */
  EAttribute getOpenUrl_Url();

  /**
   * Returns the meta object for class '{@link fr.imt.bertin.dala.project.browser.ClickLink <em>Click Link</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Click Link</em>'.
   * @see fr.imt.bertin.dala.project.browser.ClickLink
   * @generated
   */
  EClass getClickLink();

  /**
   * Returns the meta object for the attribute '{@link fr.imt.bertin.dala.project.browser.ClickLink#getLinkText <em>Link Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Link Text</em>'.
   * @see fr.imt.bertin.dala.project.browser.ClickLink#getLinkText()
   * @see #getClickLink()
   * @generated
   */
  EAttribute getClickLink_LinkText();

  /**
   * Returns the meta object for class '{@link fr.imt.bertin.dala.project.browser.ClickImage <em>Click Image</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Click Image</em>'.
   * @see fr.imt.bertin.dala.project.browser.ClickImage
   * @generated
   */
  EClass getClickImage();

  /**
   * Returns the meta object for the attribute '{@link fr.imt.bertin.dala.project.browser.ClickImage#getAltText <em>Alt Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Alt Text</em>'.
   * @see fr.imt.bertin.dala.project.browser.ClickImage#getAltText()
   * @see #getClickImage()
   * @generated
   */
  EAttribute getClickImage_AltText();

  /**
   * Returns the meta object for class '{@link fr.imt.bertin.dala.project.browser.VerifyLink <em>Verify Link</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Verify Link</em>'.
   * @see fr.imt.bertin.dala.project.browser.VerifyLink
   * @generated
   */
  EClass getVerifyLink();

  /**
   * Returns the meta object for the containment reference list '{@link fr.imt.bertin.dala.project.browser.VerifyLink#getTexts <em>Texts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Texts</em>'.
   * @see fr.imt.bertin.dala.project.browser.VerifyLink#getTexts()
   * @see #getVerifyLink()
   * @generated
   */
  EReference getVerifyLink_Texts();

  /**
   * Returns the meta object for class '{@link fr.imt.bertin.dala.project.browser.FillText <em>Fill Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fill Text</em>'.
   * @see fr.imt.bertin.dala.project.browser.FillText
   * @generated
   */
  EClass getFillText();

  /**
   * Returns the meta object for the containment reference '{@link fr.imt.bertin.dala.project.browser.FillText#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Text</em>'.
   * @see fr.imt.bertin.dala.project.browser.FillText#getText()
   * @see #getFillText()
   * @generated
   */
  EReference getFillText_Text();

  /**
   * Returns the meta object for the attribute '{@link fr.imt.bertin.dala.project.browser.FillText#getField <em>Field</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Field</em>'.
   * @see fr.imt.bertin.dala.project.browser.FillText#getField()
   * @see #getFillText()
   * @generated
   */
  EAttribute getFillText_Field();

  /**
   * Returns the meta object for class '{@link fr.imt.bertin.dala.project.browser.ClickButton <em>Click Button</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Click Button</em>'.
   * @see fr.imt.bertin.dala.project.browser.ClickButton
   * @generated
   */
  EClass getClickButton();

  /**
   * Returns the meta object for the attribute '{@link fr.imt.bertin.dala.project.browser.ClickButton#getButtonText <em>Button Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Button Text</em>'.
   * @see fr.imt.bertin.dala.project.browser.ClickButton#getButtonText()
   * @see #getClickButton()
   * @generated
   */
  EAttribute getClickButton_ButtonText();

  /**
   * Returns the meta object for class '{@link fr.imt.bertin.dala.project.browser.VerifyText <em>Verify Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Verify Text</em>'.
   * @see fr.imt.bertin.dala.project.browser.VerifyText
   * @generated
   */
  EClass getVerifyText();

  /**
   * Returns the meta object for the containment reference list '{@link fr.imt.bertin.dala.project.browser.VerifyText#getTexts <em>Texts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Texts</em>'.
   * @see fr.imt.bertin.dala.project.browser.VerifyText#getTexts()
   * @see #getVerifyText()
   * @generated
   */
  EReference getVerifyText_Texts();

  /**
   * Returns the meta object for class '{@link fr.imt.bertin.dala.project.browser.SelectOption <em>Select Option</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Select Option</em>'.
   * @see fr.imt.bertin.dala.project.browser.SelectOption
   * @generated
   */
  EClass getSelectOption();

  /**
   * Returns the meta object for the attribute '{@link fr.imt.bertin.dala.project.browser.SelectOption#getLinkText <em>Link Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Link Text</em>'.
   * @see fr.imt.bertin.dala.project.browser.SelectOption#getLinkText()
   * @see #getSelectOption()
   * @generated
   */
  EAttribute getSelectOption_LinkText();

  /**
   * Returns the meta object for class '{@link fr.imt.bertin.dala.project.browser.CheckCheckboxes <em>Check Checkboxes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Check Checkboxes</em>'.
   * @see fr.imt.bertin.dala.project.browser.CheckCheckboxes
   * @generated
   */
  EClass getCheckCheckboxes();

  /**
   * Returns the meta object for the attribute list '{@link fr.imt.bertin.dala.project.browser.CheckCheckboxes#getItems <em>Items</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Items</em>'.
   * @see fr.imt.bertin.dala.project.browser.CheckCheckboxes#getItems()
   * @see #getCheckCheckboxes()
   * @generated
   */
  EAttribute getCheckCheckboxes_Items();

  /**
   * Returns the meta object for class '{@link fr.imt.bertin.dala.project.browser.SaveLink <em>Save Link</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Save Link</em>'.
   * @see fr.imt.bertin.dala.project.browser.SaveLink
   * @generated
   */
  EClass getSaveLink();

  /**
   * Returns the meta object for the attribute '{@link fr.imt.bertin.dala.project.browser.SaveLink#getIndex <em>Index</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Index</em>'.
   * @see fr.imt.bertin.dala.project.browser.SaveLink#getIndex()
   * @see #getSaveLink()
   * @generated
   */
  EAttribute getSaveLink_Index();

  /**
   * Returns the meta object for the attribute '{@link fr.imt.bertin.dala.project.browser.SaveLink#getContainer <em>Container</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Container</em>'.
   * @see fr.imt.bertin.dala.project.browser.SaveLink#getContainer()
   * @see #getSaveLink()
   * @generated
   */
  EAttribute getSaveLink_Container();

  /**
   * Returns the meta object for class '{@link fr.imt.bertin.dala.project.browser.TextPart <em>Text Part</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Text Part</em>'.
   * @see fr.imt.bertin.dala.project.browser.TextPart
   * @generated
   */
  EClass getTextPart();

  /**
   * Returns the meta object for class '{@link fr.imt.bertin.dala.project.browser.StringLiteral <em>String Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String Literal</em>'.
   * @see fr.imt.bertin.dala.project.browser.StringLiteral
   * @generated
   */
  EClass getStringLiteral();

  /**
   * Returns the meta object for the attribute '{@link fr.imt.bertin.dala.project.browser.StringLiteral#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see fr.imt.bertin.dala.project.browser.StringLiteral#getValue()
   * @see #getStringLiteral()
   * @generated
   */
  EAttribute getStringLiteral_Value();

  /**
   * Returns the meta object for class '{@link fr.imt.bertin.dala.project.browser.VariableReference <em>Variable Reference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable Reference</em>'.
   * @see fr.imt.bertin.dala.project.browser.VariableReference
   * @generated
   */
  EClass getVariableReference();

  /**
   * Returns the meta object for the attribute '{@link fr.imt.bertin.dala.project.browser.VariableReference#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see fr.imt.bertin.dala.project.browser.VariableReference#getName()
   * @see #getVariableReference()
   * @generated
   */
  EAttribute getVariableReference_Name();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  BrowserFactory getBrowserFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link fr.imt.bertin.dala.project.browser.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.imt.bertin.dala.project.browser.impl.ModelImpl
     * @see fr.imt.bertin.dala.project.browser.impl.BrowserPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__STATEMENTS = eINSTANCE.getModel_Statements();

    /**
     * The meta object literal for the '{@link fr.imt.bertin.dala.project.browser.impl.StatementImpl <em>Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.imt.bertin.dala.project.browser.impl.StatementImpl
     * @see fr.imt.bertin.dala.project.browser.impl.BrowserPackageImpl#getStatement()
     * @generated
     */
    EClass STATEMENT = eINSTANCE.getStatement();

    /**
     * The meta object literal for the '{@link fr.imt.bertin.dala.project.browser.impl.OpenUrlImpl <em>Open Url</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.imt.bertin.dala.project.browser.impl.OpenUrlImpl
     * @see fr.imt.bertin.dala.project.browser.impl.BrowserPackageImpl#getOpenUrl()
     * @generated
     */
    EClass OPEN_URL = eINSTANCE.getOpenUrl();

    /**
     * The meta object literal for the '<em><b>Url</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPEN_URL__URL = eINSTANCE.getOpenUrl_Url();

    /**
     * The meta object literal for the '{@link fr.imt.bertin.dala.project.browser.impl.ClickLinkImpl <em>Click Link</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.imt.bertin.dala.project.browser.impl.ClickLinkImpl
     * @see fr.imt.bertin.dala.project.browser.impl.BrowserPackageImpl#getClickLink()
     * @generated
     */
    EClass CLICK_LINK = eINSTANCE.getClickLink();

    /**
     * The meta object literal for the '<em><b>Link Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLICK_LINK__LINK_TEXT = eINSTANCE.getClickLink_LinkText();

    /**
     * The meta object literal for the '{@link fr.imt.bertin.dala.project.browser.impl.ClickImageImpl <em>Click Image</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.imt.bertin.dala.project.browser.impl.ClickImageImpl
     * @see fr.imt.bertin.dala.project.browser.impl.BrowserPackageImpl#getClickImage()
     * @generated
     */
    EClass CLICK_IMAGE = eINSTANCE.getClickImage();

    /**
     * The meta object literal for the '<em><b>Alt Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLICK_IMAGE__ALT_TEXT = eINSTANCE.getClickImage_AltText();

    /**
     * The meta object literal for the '{@link fr.imt.bertin.dala.project.browser.impl.VerifyLinkImpl <em>Verify Link</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.imt.bertin.dala.project.browser.impl.VerifyLinkImpl
     * @see fr.imt.bertin.dala.project.browser.impl.BrowserPackageImpl#getVerifyLink()
     * @generated
     */
    EClass VERIFY_LINK = eINSTANCE.getVerifyLink();

    /**
     * The meta object literal for the '<em><b>Texts</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VERIFY_LINK__TEXTS = eINSTANCE.getVerifyLink_Texts();

    /**
     * The meta object literal for the '{@link fr.imt.bertin.dala.project.browser.impl.FillTextImpl <em>Fill Text</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.imt.bertin.dala.project.browser.impl.FillTextImpl
     * @see fr.imt.bertin.dala.project.browser.impl.BrowserPackageImpl#getFillText()
     * @generated
     */
    EClass FILL_TEXT = eINSTANCE.getFillText();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FILL_TEXT__TEXT = eINSTANCE.getFillText_Text();

    /**
     * The meta object literal for the '<em><b>Field</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FILL_TEXT__FIELD = eINSTANCE.getFillText_Field();

    /**
     * The meta object literal for the '{@link fr.imt.bertin.dala.project.browser.impl.ClickButtonImpl <em>Click Button</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.imt.bertin.dala.project.browser.impl.ClickButtonImpl
     * @see fr.imt.bertin.dala.project.browser.impl.BrowserPackageImpl#getClickButton()
     * @generated
     */
    EClass CLICK_BUTTON = eINSTANCE.getClickButton();

    /**
     * The meta object literal for the '<em><b>Button Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLICK_BUTTON__BUTTON_TEXT = eINSTANCE.getClickButton_ButtonText();

    /**
     * The meta object literal for the '{@link fr.imt.bertin.dala.project.browser.impl.VerifyTextImpl <em>Verify Text</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.imt.bertin.dala.project.browser.impl.VerifyTextImpl
     * @see fr.imt.bertin.dala.project.browser.impl.BrowserPackageImpl#getVerifyText()
     * @generated
     */
    EClass VERIFY_TEXT = eINSTANCE.getVerifyText();

    /**
     * The meta object literal for the '<em><b>Texts</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VERIFY_TEXT__TEXTS = eINSTANCE.getVerifyText_Texts();

    /**
     * The meta object literal for the '{@link fr.imt.bertin.dala.project.browser.impl.SelectOptionImpl <em>Select Option</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.imt.bertin.dala.project.browser.impl.SelectOptionImpl
     * @see fr.imt.bertin.dala.project.browser.impl.BrowserPackageImpl#getSelectOption()
     * @generated
     */
    EClass SELECT_OPTION = eINSTANCE.getSelectOption();

    /**
     * The meta object literal for the '<em><b>Link Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SELECT_OPTION__LINK_TEXT = eINSTANCE.getSelectOption_LinkText();

    /**
     * The meta object literal for the '{@link fr.imt.bertin.dala.project.browser.impl.CheckCheckboxesImpl <em>Check Checkboxes</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.imt.bertin.dala.project.browser.impl.CheckCheckboxesImpl
     * @see fr.imt.bertin.dala.project.browser.impl.BrowserPackageImpl#getCheckCheckboxes()
     * @generated
     */
    EClass CHECK_CHECKBOXES = eINSTANCE.getCheckCheckboxes();

    /**
     * The meta object literal for the '<em><b>Items</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHECK_CHECKBOXES__ITEMS = eINSTANCE.getCheckCheckboxes_Items();

    /**
     * The meta object literal for the '{@link fr.imt.bertin.dala.project.browser.impl.SaveLinkImpl <em>Save Link</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.imt.bertin.dala.project.browser.impl.SaveLinkImpl
     * @see fr.imt.bertin.dala.project.browser.impl.BrowserPackageImpl#getSaveLink()
     * @generated
     */
    EClass SAVE_LINK = eINSTANCE.getSaveLink();

    /**
     * The meta object literal for the '<em><b>Index</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SAVE_LINK__INDEX = eINSTANCE.getSaveLink_Index();

    /**
     * The meta object literal for the '<em><b>Container</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SAVE_LINK__CONTAINER = eINSTANCE.getSaveLink_Container();

    /**
     * The meta object literal for the '{@link fr.imt.bertin.dala.project.browser.impl.TextPartImpl <em>Text Part</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.imt.bertin.dala.project.browser.impl.TextPartImpl
     * @see fr.imt.bertin.dala.project.browser.impl.BrowserPackageImpl#getTextPart()
     * @generated
     */
    EClass TEXT_PART = eINSTANCE.getTextPart();

    /**
     * The meta object literal for the '{@link fr.imt.bertin.dala.project.browser.impl.StringLiteralImpl <em>String Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.imt.bertin.dala.project.browser.impl.StringLiteralImpl
     * @see fr.imt.bertin.dala.project.browser.impl.BrowserPackageImpl#getStringLiteral()
     * @generated
     */
    EClass STRING_LITERAL = eINSTANCE.getStringLiteral();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRING_LITERAL__VALUE = eINSTANCE.getStringLiteral_Value();

    /**
     * The meta object literal for the '{@link fr.imt.bertin.dala.project.browser.impl.VariableReferenceImpl <em>Variable Reference</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.imt.bertin.dala.project.browser.impl.VariableReferenceImpl
     * @see fr.imt.bertin.dala.project.browser.impl.BrowserPackageImpl#getVariableReference()
     * @generated
     */
    EClass VARIABLE_REFERENCE = eINSTANCE.getVariableReference();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE_REFERENCE__NAME = eINSTANCE.getVariableReference_Name();

  }

} //BrowserPackage
