/**
 * generated by Xtext 2.36.0
 */
package fr.imt.bertin.dala.project.browser;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see fr.imt.bertin.dala.project.browser.BrowserPackage
 * @generated
 */
public interface BrowserFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  BrowserFactory eINSTANCE = fr.imt.bertin.dala.project.browser.impl.BrowserFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Statement</em>'.
   * @generated
   */
  Statement createStatement();

  /**
   * Returns a new object of class '<em>Open Url</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Open Url</em>'.
   * @generated
   */
  OpenUrl createOpenUrl();

  /**
   * Returns a new object of class '<em>Click Link</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Click Link</em>'.
   * @generated
   */
  ClickLink createClickLink();

  /**
   * Returns a new object of class '<em>Click Image</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Click Image</em>'.
   * @generated
   */
  ClickImage createClickImage();

  /**
   * Returns a new object of class '<em>Verify Link</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Verify Link</em>'.
   * @generated
   */
  VerifyLink createVerifyLink();

  /**
   * Returns a new object of class '<em>Fill Text</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Fill Text</em>'.
   * @generated
   */
  FillText createFillText();

  /**
   * Returns a new object of class '<em>Click Button</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Click Button</em>'.
   * @generated
   */
  ClickButton createClickButton();

  /**
   * Returns a new object of class '<em>Verify Text</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Verify Text</em>'.
   * @generated
   */
  VerifyText createVerifyText();

  /**
   * Returns a new object of class '<em>Select Option</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Select Option</em>'.
   * @generated
   */
  SelectOption createSelectOption();

  /**
   * Returns a new object of class '<em>Check Checkboxes</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Check Checkboxes</em>'.
   * @generated
   */
  CheckCheckboxes createCheckCheckboxes();

  /**
   * Returns a new object of class '<em>Save Link</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Save Link</em>'.
   * @generated
   */
  SaveLink createSaveLink();

  /**
   * Returns a new object of class '<em>Text Part</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Text Part</em>'.
   * @generated
   */
  TextPart createTextPart();

  /**
   * Returns a new object of class '<em>String Literal</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>String Literal</em>'.
   * @generated
   */
  StringLiteral createStringLiteral();

  /**
   * Returns a new object of class '<em>Variable Reference</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Variable Reference</em>'.
   * @generated
   */
  VariableReference createVariableReference();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  BrowserPackage getBrowserPackage();

} //BrowserFactory
