/**
 * generated by Xtext 2.36.0
 */
package fr.imt.bertin.dala.project.browser;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Click Image</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.imt.bertin.dala.project.browser.ClickImage#getAltText <em>Alt Text</em>}</li>
 * </ul>
 *
 * @see fr.imt.bertin.dala.project.browser.BrowserPackage#getClickImage()
 * @model
 * @generated
 */
public interface ClickImage extends Statement
{
  /**
   * Returns the value of the '<em><b>Alt Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Alt Text</em>' attribute.
   * @see #setAltText(String)
   * @see fr.imt.bertin.dala.project.browser.BrowserPackage#getClickImage_AltText()
   * @model
   * @generated
   */
  String getAltText();

  /**
   * Sets the value of the '{@link fr.imt.bertin.dala.project.browser.ClickImage#getAltText <em>Alt Text</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Alt Text</em>' attribute.
   * @see #getAltText()
   * @generated
   */
  void setAltText(String value);

} // ClickImage
