/**
 * generated by Xtext 2.36.0
 */
package fr.imt.bertin.dala.project.browser;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Click Button</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.imt.bertin.dala.project.browser.ClickButton#getButtonText <em>Button Text</em>}</li>
 * </ul>
 *
 * @see fr.imt.bertin.dala.project.browser.BrowserPackage#getClickButton()
 * @model
 * @generated
 */
public interface ClickButton extends Statement
{
  /**
   * Returns the value of the '<em><b>Button Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Button Text</em>' attribute.
   * @see #setButtonText(String)
   * @see fr.imt.bertin.dala.project.browser.BrowserPackage#getClickButton_ButtonText()
   * @model
   * @generated
   */
  String getButtonText();

  /**
   * Sets the value of the '{@link fr.imt.bertin.dala.project.browser.ClickButton#getButtonText <em>Button Text</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Button Text</em>' attribute.
   * @see #getButtonText()
   * @generated
   */
  void setButtonText(String value);

} // ClickButton
