/**
 * generated by Xtext 2.36.0
 */
package fr.imt.bertin.dala.project.browser;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Click Link</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.imt.bertin.dala.project.browser.ClickLink#getLinkText <em>Link Text</em>}</li>
 * </ul>
 *
 * @see fr.imt.bertin.dala.project.browser.BrowserPackage#getClickLink()
 * @model
 * @generated
 */
public interface ClickLink extends Statement
{
  /**
   * Returns the value of the '<em><b>Link Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Link Text</em>' attribute.
   * @see #setLinkText(String)
   * @see fr.imt.bertin.dala.project.browser.BrowserPackage#getClickLink_LinkText()
   * @model
   * @generated
   */
  String getLinkText();

  /**
   * Sets the value of the '{@link fr.imt.bertin.dala.project.browser.ClickLink#getLinkText <em>Link Text</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Link Text</em>' attribute.
   * @see #getLinkText()
   * @generated
   */
  void setLinkText(String value);

} // ClickLink
