/**
 * generated by Xtext 2.36.0
 */
package fr.imt.bertin.dala.project.browser;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Fill Text</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.imt.bertin.dala.project.browser.FillText#getText <em>Text</em>}</li>
 *   <li>{@link fr.imt.bertin.dala.project.browser.FillText#getField <em>Field</em>}</li>
 * </ul>
 *
 * @see fr.imt.bertin.dala.project.browser.BrowserPackage#getFillText()
 * @model
 * @generated
 */
public interface FillText extends Statement
{
  /**
   * Returns the value of the '<em><b>Text</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Text</em>' containment reference.
   * @see #setText(TextPart)
   * @see fr.imt.bertin.dala.project.browser.BrowserPackage#getFillText_Text()
   * @model containment="true"
   * @generated
   */
  TextPart getText();

  /**
   * Sets the value of the '{@link fr.imt.bertin.dala.project.browser.FillText#getText <em>Text</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Text</em>' containment reference.
   * @see #getText()
   * @generated
   */
  void setText(TextPart value);

  /**
   * Returns the value of the '<em><b>Field</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Field</em>' attribute.
   * @see #setField(String)
   * @see fr.imt.bertin.dala.project.browser.BrowserPackage#getFillText_Field()
   * @model
   * @generated
   */
  String getField();

  /**
   * Sets the value of the '{@link fr.imt.bertin.dala.project.browser.FillText#getField <em>Field</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Field</em>' attribute.
   * @see #getField()
   * @generated
   */
  void setField(String value);

} // FillText
