/**
 * generated by Xtext 2.36.0
 */
package fr.imt.bertin.dala.project.browser;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Save Link</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.imt.bertin.dala.project.browser.SaveLink#getIndex <em>Index</em>}</li>
 *   <li>{@link fr.imt.bertin.dala.project.browser.SaveLink#getContainer <em>Container</em>}</li>
 * </ul>
 *
 * @see fr.imt.bertin.dala.project.browser.BrowserPackage#getSaveLink()
 * @model
 * @generated
 */
public interface SaveLink extends Statement
{
  /**
   * Returns the value of the '<em><b>Index</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Index</em>' attribute.
   * @see #setIndex(int)
   * @see fr.imt.bertin.dala.project.browser.BrowserPackage#getSaveLink_Index()
   * @model
   * @generated
   */
  int getIndex();

  /**
   * Sets the value of the '{@link fr.imt.bertin.dala.project.browser.SaveLink#getIndex <em>Index</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Index</em>' attribute.
   * @see #getIndex()
   * @generated
   */
  void setIndex(int value);

  /**
   * Returns the value of the '<em><b>Container</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Container</em>' attribute.
   * @see #setContainer(String)
   * @see fr.imt.bertin.dala.project.browser.BrowserPackage#getSaveLink_Container()
   * @model
   * @generated
   */
  String getContainer();

  /**
   * Sets the value of the '{@link fr.imt.bertin.dala.project.browser.SaveLink#getContainer <em>Container</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Container</em>' attribute.
   * @see #getContainer()
   * @generated
   */
  void setContainer(String value);

} // SaveLink
