/**
 * generated by Xtext 2.36.0
 */
package fr.imt.bertin.dala.project.browser;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.imt.bertin.dala.project.browser.BrowserPackage#getStatement()
 * @model
 * @generated
 */
public interface Statement extends EObject
{
} // Statement
