/**
 * generated by Xtext 2.36.0
 */
package fr.imt.bertin.dala.project.browser;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>String Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.imt.bertin.dala.project.browser.StringLiteral#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see fr.imt.bertin.dala.project.browser.BrowserPackage#getStringLiteral()
 * @model
 * @generated
 */
public interface StringLiteral extends TextPart
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see fr.imt.bertin.dala.project.browser.BrowserPackage#getStringLiteral_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link fr.imt.bertin.dala.project.browser.StringLiteral#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

} // StringLiteral
