/**
 * generated by Xtext 2.36.0
 */
package fr.imt.bertin.dala.project.browser;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Verify Text</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.imt.bertin.dala.project.browser.VerifyText#getTexts <em>Texts</em>}</li>
 * </ul>
 *
 * @see fr.imt.bertin.dala.project.browser.BrowserPackage#getVerifyText()
 * @model
 * @generated
 */
public interface VerifyText extends Statement
{
  /**
   * Returns the value of the '<em><b>Texts</b></em>' containment reference list.
   * The list contents are of type {@link fr.imt.bertin.dala.project.browser.TextPart}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Texts</em>' containment reference list.
   * @see fr.imt.bertin.dala.project.browser.BrowserPackage#getVerifyText_Texts()
   * @model containment="true"
   * @generated
   */
  EList<TextPart> getTexts();

} // VerifyText
