/*
 * generated by Xtext 2.36.0
 */
package fr.imt.bertin.dala.project.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractBrowserValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(fr.imt.bertin.dala.project.browser.BrowserPackage.eINSTANCE);
		return result;
	}
}
