/*
 * generated by Xtext 2.36.0
 */
package fr.imt.bertin.dala.project.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractBrowserScopeProvider extends DelegatingScopeProvider {
}
